apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoiYXV0aHMiOiB7CiJyZWdpc3RyeS55YW5kZXgubmV0Ijoge30sCiJnaGNyLmlvIjogewoiYXV0aCI6ICJiV1ZzYm1sck9EZzZaMmh3WDNSa1lrNW5NVlJ1YzA1SWNEUkxVRXRtWW0wMllrdEtiVloyTVVRMGR6RXdaMlZJUnc9PSIKfQp9LAoiY3VycmVudENvbnRleHQiOiAiY29saW1hIiwKImV4cGVyaW1lbnRhbCI6ICJkaXNhYmxlZCIKfQo=
type: kubernetes.io/dockerconfigjson
