apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJiV1ZzYm1sck9EZzZaMmh3WDFWVE5YZHZkRkprYkRWT1VGWXpXREJOUjBsWGFYRnhUamxQTTNWWmFUTlhia3A2TUE9PSJ9fX0K
type: kubernetes.io/dockerconfigjson
